export interface CommonState {
  darkMode: boolean;
}
export interface RootState {
  headerCollapse: boolean; // Assuming headerCollapse is a boolean value
}
export interface TableData {
  Apr: any;
  Mar: any;
  Feb: any;
  Jan: any;
  Dec: any;
  Nov: any;
  Oct: any;
  Sep: any;
  Aug: any;
  Jul: any;
  Jun: any;
  dob: any;
  parent: any;
  refId: any;
  mode: any;
  datePaid: any;
  discount: any;
  fine: any;
  balance: any;
  medicalUsed: any;
  medicalAvailable: any;
  casualUsed: any;
  casualAvailable: any;
  maternityUsed: any;
  maternityAvailable: any;
  paternityUsed: any;
  paternityAvailable: any;
  specialUsed: any;
  specialAvailable: any;
  percent: any;
  total: any;
  envScience: any;
  computer: any;
  maths: any;
  chemistry: any;
  physics: any;
  spanish: any;
  english: any;
  message: any;
  contact: any;
  dateAdded: any;
  countryCode: any;
  cityName: any;
  stateName: any;
  countryName: any;
  comment: any;
  review: any;
  blog: any;
  tags: any;
  page: any;
  slug: any;
  rtl: any;
  language: any;
  allowAll: any;
  delete: any;
  edit: any;
  modules: any;
  createdBy: any;
  dateOfJoined: any;
  createdOn: any;
  deleteRequestDate: any;
  requisitionDate: any;
  transactionDate: any;
  planType: any;
  providerName: any;
  invoiceNumber: any;
  method:string;
  incomeName: any;
  attendance: any;
  notes: any;
  classe: any;
  rollNo: any;
  admissionNo: any;
  authority: any;
  noofDays: any;
  submittedBy: any;
  sectionName: any;
  sNo: string;
  view: any;
  salaryFor: any;
  netSalary: any;
  details: any;
  holidayTitle: any;
  Result: any;
  Percent: any;
  Total: any;
  EnvScience: any;
  Computer: any;
  Maths: any;
  Chemistry: any;
  Physics: any;
  Spanish: any;
  English: any;
  studentName: any;
  submissionDate: any;
  homeworkDate: any;
  subject: any;
  code: any;
  subjectGroup: any;
  noOfSubjects: any;
  noOfStudents: any;
  capacity: string;
  reason: string;
  role: string;
  examName: string;
  minMarks: string;
  maxMarks: string;
  route: string;
  roomNo: string;
  duration: string;
  endTime: string;
  startTime: string;
  examDate: string;
  gradePoints: string;
  percentage: string;
  grade: string;
  dateOfJoin: string;
  designation: string;
  department: string;
  id: any;
  questions: string;
  answers: string;
  created_at: string;
  name: string;
  type: string;
  progress: string;
  members: string;
  startDate: string;
  endDate: string;
  lead_name: string;
  company_address: string;
  pages: string;
  page_slug: string;
  phone: string;
  company_name: string;
  location: string;
  Action: string;
  rating: string;
  owner: string;
  created: string;
  leadName: string;
  companyName: string;
  source: string;
  leadOwner: string;
  createdDate: string;
  leadStatus: string;
  email: string;
  Stage: string;
  Deal_Value: string;
  close_date: string;
  Probability: string;
  Status: string;
  created_date: string;
  Deal_Name: string;
  industry: string;
  company: string;
  wonDeals: string;
  lostDeals: string;
  dateCreated: string;
  budgetValue: string;
  currentlySpend: string;
  pipelineStage: string;
  client: string;
  addedOn: string;
  priority: string;
  dueDate: string;
  taskName: string;
  assignedTo: string;
  status: string;
  createdAt: string;
  driverLicenseNo: string;
  title: string;
  roleName: string;
  paymentType: string;
  createdat: string;
  vehicle: string;
  no_deal: string;
  deal_value: string;
  stage: string;
  dealValue: string;
  start_date: string;
  end_date: string;
  piority: string;
  customer_no: string;
  customer_name: string;
  content: string;
  userName: string;
  position: string;
  office: string;
  age: string;
  salary: string;
  class: string;
  section: string;
  mark: string;
  marks: string;
  cgpa: string;
  exams: string;
  ownedMemberImgSrc: string;
  imgSrc: string;
  mobile: string;
  action: string;
  ownedMember: string;
  size: string;
  lastModified: string;
  AdmissionNo: string;
  RollNo: string;
  DateofJoin: string;
  noofBed: string;
  DOB: string;
  gender: string;
  leaveType: string;
  leaveDate: string;
  noOfDays: string;
  appliedOn: string;
  jan: string;
  feb: string;
  mar: string;
  apr: string;
  may: string;
  jun: string;
  jul: string;
  aug: string;
  sep: string;
  oct: string;
  nov: string;
  dec: string;
  result: string;
  promotion: number;
  dateofJoin: string;
  Child: string;
  count: string;
  expenseName: any;
  description: any;
  category: any;
  date: any;
  amount: any;
  invoiceNo: any;
  paymentMethod: any;
  feesGroup:string;
  feesCode:string;
  present:string;
  absent:string;
  percentange:string;
  absentPercentange:string;
  feesType:string;
  fineType:string;
  fineAmount:string;
  admNo:string;
  lastDate:string;
  student:string;
  cardNo:string;
  fname:string;
  bookName:string;
  bookNo:string;
  publisher:string;
  author:string;
  rackNo:string;
  qty:string;
  available:string;
  price:string;
  postDate:string;
  dateofIssue:string;
  issueTo:string;
  booksIssued:string;
  bookReturned:string;
  issueRemarks:string;
  year:string;
  coachName:string;
  sports:string;
  hostelName:string;
  hostelType:string;
  address:string;
  inTake:string;
  roomType:string;
  routes:string;
  pickupPoint:string;
  vehicleNo:string;
  gps:string;
  chassisNo:string;
  registrationNo:string;
  madeofYear:string;
  vehicleModel:string;
  key:string;

}
export interface status {
  text: string;
  status: string;
}

export interface DatatableProps {
  columns: any[]; // You can replace `any[]` with the specific type of columns you expect
  dataSource: any[]; // You can replace `any[]` with the specific type of dataSource you expect
  Selection?: boolean | undefined;
}

export interface CountriesData {
  name: string;
  countryName: string;
  countryId: string;
  startDate: string;
  endDate: string;
  countryCode: string;
}
export interface DealsInterface {
  dealName: string;
  stage: string;
  dealValue: string;
  tag1: string;
  closeDate: string;
  crearedDate: string;
  owner: string;
  status: string;
  probability: string;
}
export interface DeleteRequestInterface {
  id: number;
  si_no: string;
  select: string;
  customer_name: string;
  customer_image: string;
  customer_no: string;
  created: string;
  delete_request: string;
  Action: string;
}
export interface AppState {
  mouseOverSidebar: string;
}
